spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    2-4
    url: jdbc:mysql://47.100.32.48:3306/oomall?useUnicode=true&characterEncoding=utf8

    #    3-6
#    url: jdbc:mysql://47.103.218.171:3306/oomall2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

    #    3-8
    #    url: jdbc:mysql://47.103.218.171:3306/oomall2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

    #    2-1
    #    url: jdbc:mysql://47.103.218.171:3306/oomall2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

    #    2-2
    #    url: jdbc:mysql://47.103.218.171:3306/oomall2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

    #   2-4
    username: test
    password: test

    #    3-6
#    username: root
#    password: 741120ab

    #    3-8


    #    2-1


    #    2-2
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #  最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
  redis:
    port: 6379
    host: 47.100.32.48
    password: ooad
